### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by majovec** [erkam2002/AntiWin10#1]
Very very bad plugins :D ( i play on win10 ) and good code :D

**Comment by erkam2002** [comment]
?

**Comment by majovec** [comment]
oh on pe.gameteam.cz is pe arenas (we use nukkit )

**Comment by majovec** [comment]
and do you please help me ?

**Comment by erkam2002** [comment]
Do you use Twitter or Discord ? @ErkamKahriman MCPEExpert#2483

**Comment by majovec** [comment]
look on discord
